<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="6" hostname="MJLT-2643" name="com.Dynamicity.BidSubmissionFor1stSupplier_Dynamically_test" tests="7" failures="0" timestamp="2024-06-02T15:17:56 IST" time="0.313" errors="1">
  <testcase name="BidSubmission1stSupplier_Dynamically" time="0.000" classname="com.Dynamicity.BidSubmissionFor1stSupplier_Dynamically_test">
    <skipped/>
  </testcase> <!-- BidSubmission1stSupplier_Dynamically -->
  <system-out/>
  <testcase name="CaptureJSResponse" time="0.313" classname="com.Dynamicity.BidSubmissionFor1stSupplier_Dynamically_test">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.Dynamicity.BidSubmissionFor1stSupplier_Dynamically_test.CaptureJSResponse(BidSubmissionFor1stSupplier_Dynamically_test.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:619)
at org.testng.TestRunner.beforeRun(TestRunner.java:609)
at org.testng.TestRunner.run(TestRunner.java:580)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- CaptureJSResponse -->
  <system-out/>
  <testcase name="BidSubmission5thSupplier_Dynamically" time="0.000" classname="com.Dynamicity.BidSubmissionFor1stSupplier_Dynamically_test">
    <skipped/>
  </testcase> <!-- BidSubmission5thSupplier_Dynamically -->
  <system-out/>
  <testcase name="BidSubmission3rdSupplier_Dynamically" time="0.000" classname="com.Dynamicity.BidSubmissionFor1stSupplier_Dynamically_test">
    <skipped/>
  </testcase> <!-- BidSubmission3rdSupplier_Dynamically -->
  <system-out/>
  <testcase name="BidSubmission4thSupplier_Dynamically" time="0.000" classname="com.Dynamicity.BidSubmissionFor1stSupplier_Dynamically_test">
    <skipped/>
  </testcase> <!-- BidSubmission4thSupplier_Dynamically -->
  <system-out/>
  <testcase name="BidSubmission2ndSupplier_Dynamically" time="0.000" classname="com.Dynamicity.BidSubmissionFor1stSupplier_Dynamically_test">
    <skipped/>
  </testcase> <!-- BidSubmission2ndSupplier_Dynamically -->
  <system-out/>
  <testcase name="BidSubmission6thSupplier_Dynamically" time="0.000" classname="com.Dynamicity.BidSubmissionFor1stSupplier_Dynamically_test">
    <skipped/>
  </testcase> <!-- BidSubmission6thSupplier_Dynamically -->
  <system-out/>
</testsuite> <!-- com.Dynamicity.BidSubmissionFor1stSupplier_Dynamically_test -->
